### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-daynight-theme#2]
### To-Do List
- [x] Implement basic switchform
- [x] Implement night.css
- [ ] Clean up codebase.

**Comment by WebCrew** [comment]
Any CSS things to handle? Is there a online version of the theme wehre I can see it in action and work on it? I have no HH installed so far thats why I`m asking for a online version of the theme ;)

Private Question: Sarah would You be so kind to traslate me these to things into japanese please:

1.: Andreas Holzer
2.: strong as the sun

**Comment by Felli** [comment]
> Any CSS things to handle? Is there a online version of the theme wehre I can see it in action and work on it? I have no HH installed so far thats why I`m asking for a online version of the theme ;)

At the moment this theme is onhold for update to 1.3 beta, also sorry, no online places for the public just yet.

> Private Question: Sarah would You be so kind to traslate me these to things into Japanese please:

1.: アンドレアス・ホルツァー
2.: 太陽のように強い

**Comment by WebCrew** [comment]
Ok Sarah thank You very much :)
If there is a CSS thing to do le me know it please ;)
I hope You are fine?
Thanks also for the translation thats awesome :)

**Comment by Felli** [comment]
If you want to check out our latest theme release check out [Outer Limits](https://github.com/GreenMeteor/humhub-outerlimits-theme). :+1:

**Comment by WebCrew** [comment]
Ok I`ll take a look at it :)
